name: Build for macOS 13

env:
  ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: push
  # workflow_dispatch:
  #   inputs:
  #     tags:
  #       description: 'Build tags'

jobs:
  build_mac_13:
    # if: ${{ github.actor == 'badabing2005' }}
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Homebrew
        run: brew update

      # To fix linkage issues during below brew install
      - name: Relink Python
        run: |
          brew unlink python@3.11 python@3.12 
          brew link --overwrite python@3.11 python@3.12

      - name: Install node, graphicsmagick, imagemagick, wxpython
        run: brew install node graphicsmagick imagemagick wxpython
        env: 
         # To avoid a lot of unrelated software upgrades
         HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1

      - name: Install create-dmg
        run: npm install --global create-dmg

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      - name: List modules and their versions
        run: python -m pip freeze

      - name: Build application
        run: ./build.sh

      - name: Rename the file
        run: mv dist/PixelFlasher.dmg dist/PixelFlasher_MacOS_13.dmg

      - name: Get sha256
        run: |
          shasum -a 256 dist/PixelFlasher_MacOS_13.dmg > dist/PixelFlasher_MacOS_13.dmg.sha256
          cat dist/PixelFlasher_MacOS_13.dmg.sha256

      - name: List contents of dist directory
        run: ls dist

      - name: Upload Mac-OS 13 Artifact
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }} # Only run this step when running in GitHub Actions
        uses: actions/upload-artifact@v4
        id: upload_artifact_macos_13
        with:
          name: PixelFlasher_MacOS_13.dmg Artifacts
          path: |
            dist/PixelFlasher_MacOS_13.dmg
            dist/PixelFlasher_MacOS_13.dmg.sha256

