name: Build for All platforms

env:
  ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the workflow will run
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: 'Build tags'

jobs:
  build_windows_2019:
    uses: ./.github/workflows/windows_2019.yml
    
  build_windows_2022:
    uses: ./.github/workflows/windows_2022.yml

  build_ubuntu_20_04:
    uses: ./.github/workflows/ubuntu_20_04.yml

  build_ubuntu_22_04:
    uses: ./.github/workflows/ubuntu_22_04.yml

  build_mac_13:
    uses: ./.github/workflows/mac_13.yml

  deploy:
    needs: [
      build_windows_2019, 
      build_windows_2022,
      build_ubuntu_20_04,
      build_ubuntu_22_04,
      build_mac_13
    ]

    runs-on: ubuntu-latest

    steps:
      # Get version
      - name: Get version from tag
        id: get_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
              version=${GITHUB_REF#refs/tags/v}
          else
              version=0.0.0.${GITHUB_REF#refs/heads/}
          fi
          echo "version=${version}" >> "${GITHUB_OUTPUT}"

      # Download the Windows artifact from the build_windows job
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: PixelFlasher.exe Artifacts
          path: release
        continue-on-error: true

      # Download the Windows-2019 artifact from the build_windows_2019 job
      - name: Download Windows-2019 Artifact
        uses: actions/download-artifact@v4
        with:
          name: PixelFlasher_Win_2019.exe Artifacts
          path: release
        continue-on-error: true

      # Download the Ubuntu_20_04 artifact from the build_ubuntu_20_04 job
      - name: Download Ubuntu_20_04 Artifact
        uses: actions/download-artifact@v4
        with:
          name: PixelFlasher_Ubuntu_20_04 Artifacts
          path: release
        continue-on-error: true

      # Download the Ubuntu_22_04 artifact from the build_ubuntu_22_04 job
      - name: Download Ubuntu_22_04 Artifact
        uses: actions/download-artifact@v4
        with:
          name: PixelFlasher_Ubuntu_22_04 Artifacts
          path: release
        continue-on-error: true

      # Download the Mac-OS artifacts from the build_mac_13 job
      - name: Download Mac-OS Artifacts
        uses: actions/download-artifact@v4
        with:
          name: PixelFlasher.dmg Artifacts
          path: release
        continue-on-error: true

      # List the artifacts downloaded
      - name: List contents of dist directory
        run: ls ${{ github.workspace }}/release*

      - name: Create release
        id: create_release
        # uses: softprops/action-gh-release@v1
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          # body_path: RELEASE.md
          draft: true
          prerelease: false
          files: |
            release/*
        continue-on-error: true
